services:
  - type: web
    name: synchronie-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      echo "📦 Dépendances installées"
    startCommand: |
      FLASK_APP=run.py flask db upgrade || python fix_db.py
      gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_CONFIG
        value: production
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: synchronie-db
          property: connectionString
    healthCheckPath: /api/health

  - type: pserv
    name: synchronie-db
    env: postgres
    plan: free
    databaseName: synchronie
    databaseUser: synchronie_user
