services:
  - type: web
    name: synchronie
    env: python
    plan: free
    buildCommand: "./.render-build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@synchronie.fr
      - key: ADMIN_PASSWORD
        generateValue: true

  - type: pserv
    name: synchronie-db
    plan: free
    env: postgresql
    region: frankfurt
