services:
  - type: web
    name: synchronie
    env: python
    plan: free
    buildCommand: "./.render-build.sh"
    startCommand: "gunicorn wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
